-- Создаем таблицу 'profiles', только если она не существует
CREATE TABLE IF NOT EXISTS public.profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT UNIQUE NOT NULL,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    chat_id BIGINT NOT NULL,
    gender TEXT CHECK (gender IN ('male', 'female')),
    age INT,
    height_cm INT,
    weight_kg NUMERIC(5, 2),
    goal TEXT CHECK (goal IN ('lose_weight', 'maintain_weight', 'gain_mass')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Создаем таблицу 'meals', только если она не существует
CREATE TABLE IF NOT EXISTS public.meals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    calories INT NOT NULL,
    protein NUMERIC(5, 2),
    fat NUMERIC(5, 2),
    carbs NUMERIC(5, 2),
    meal_type TEXT, -- e.g., 'photo', 'manual'
    photo_url TEXT, -- Link to the photo if available
    eaten_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Добавляем колонку 'weight_g' в таблицу 'meals', если ее нет
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS weight_g INT;

-- Добавляем колонку 'ingredients' в таблицу 'meals', если ее нет
ALTER TABLE public.meals ADD COLUMN IF NOT EXISTS ingredients TEXT[];

-- Добавляем колонки для дневной нормы КБЖУ в таблицу 'profiles', если их нет
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS daily_calories NUMERIC;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS daily_protein NUMERIC;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS daily_fat NUMERIC;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS daily_carbs NUMERIC;

    SELECT
        con.conname AS constraint_name,
        ccu.table_schema AS table_schema,
        ccu.table_name,
        ccu.column_name,
        pg_get_constraintdef(con.oid) AS definition
    FROM
        pg_constraint AS con
    JOIN
        pg_namespace AS n ON n.oid = con.connamespace
    JOIN
        information_schema.constraint_column_usage AS ccu ON con.conname = ccu.constraint_name AND n.nspname = ccu.table_schema
    WHERE
        con.contype = 'c' AND ccu.table_name = 'profiles';

SELECT * FROM pg_policies WHERE tablename = 'meals';

-- Таблица для данных планов тренировок
CREATE TABLE IF NOT EXISTS public.workout_plan_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    experience TEXT NOT NULL, -- beginner, intermediate, advanced
    goal TEXT NOT NULL, -- weightloss, muscle, maintain, health
    priority_zones TEXT[], -- массив зон: back, chest, legs, shoulders, core
    injuries TEXT, -- описание травм или 'none'
    location TEXT NOT NULL, -- home, gym, outdoor
    frequency_per_week INT NOT NULL, -- количество тренировок в неделю
    duration_minutes INT NOT NULL, -- продолжительность одной тренировки
    preferred_types TEXT[], -- массив типов: strength, cardio, hiit, yoga, stretching
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Таблица для данных планов питания
CREATE TABLE IF NOT EXISTS public.nutrition_plan_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    activity_level TEXT NOT NULL, -- sedentary, light, active, heavy
    calorie_goal TEXT NOT NULL, -- deficit, surplus, maintain
    allergies TEXT[], -- массив аллергий или ['none']
    diet_type TEXT NOT NULL, -- regular, vegetarian, vegan, keto
    meals_per_day TEXT NOT NULL, -- three_main, five_six_small
    product_limitations TEXT, -- описание ограничений или 'none'
    supplements_interest TEXT NOT NULL, -- yes, no
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Создаем политики для полного доступа
CREATE POLICY "Allow public all operations on workout_plan_data" 
ON workout_plan_data FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Allow public all operations on nutrition_plan_data" 
ON nutrition_plan_data FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

-- Создаём таблицу water_intake с правильными типами данных
CREATE TABLE water_intake (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    amount_ml INTEGER NOT NULL CHECK (amount_ml > 0),
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Создаём индексы
CREATE INDEX idx_water_intake_user_id ON water_intake(user_id);
CREATE INDEX idx_water_intake_recorded_at ON water_intake(recorded_at);

-- Включаем RLS
ALTER TABLE water_intake ENABLE ROW LEVEL SECURITY;

-- Политики RLS
CREATE POLICY "Пользователи видят свои записи" ON water_intake
    FOR ALL USING (true);

    CREATE TABLE workout_records (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    telegram_id TEXT NOT NULL,
    workout_type TEXT DEFAULT 'general',
    duration_minutes INTEGER DEFAULT 30,
    exercises TEXT,
    intensity TEXT,
    calories_burned INTEGER DEFAULT 0,
    notes TEXT,
    date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Добавляем RLS политики
ALTER TABLE workout_records ENABLE ROW LEVEL SECURITY;

-- Политика для чтения всех записей (пока простая)
CREATE POLICY "Allow read access" ON workout_records FOR SELECT USING (true);

-- Политика для вставки всех записей  
CREATE POLICY "Allow insert access" ON workout_records FOR INSERT WITH CHECK (true);

-- Добавляем колонку для целевого веса
ALTER TABLE public.profiles
ADD COLUMN target_weight_kg NUMERIC;

-- Добавляем колонку для срока достижения цели в месяцах
ALTER TABLE public.profiles
ADD COLUMN timeframe_months INT;

-- Добавляем колонку для часового пояса пользователя
ALTER TABLE public.profiles
ADD COLUMN timezone TEXT DEFAULT 'Europe/Moscow';

-- Комментарии для колонок (хорошая практика)
COMMENT ON COLUMN public.profiles.target_weight_kg IS 'Целевой вес пользователя в килограммах.';
COMMENT ON COLUMN public.profiles.timeframe_months IS 'Срок для достижения цели в месяцах.';
COMMENT ON COLUMN public.profiles.timezone IS 'Часовой пояс пользователя для персонализированных уведомлений.';

-- 🏆 СИСТЕМА ЧЕЛЛЕНДЖЕЙ - Упрощенная версия SQL для Supabase
-- Исправлены ошибки типов данных и упрощены политики безопасности

-- 1. Таблица еженедельных челленджей
CREATE TABLE IF NOT EXISTS weekly_challenges (
    id BIGSERIAL PRIMARY KEY,
    week_start TIMESTAMPTZ NOT NULL UNIQUE, -- Начало недели (понедельник)
    title TEXT NOT NULL,                    -- Название челленджа
    description TEXT NOT NULL,              -- Описание челленджа
    target_value INTEGER NOT NULL,          -- Целевое значение (например, 70000 шагов)
    unit TEXT NOT NULL,                     -- Единица измерения (шагов, литров, минут, км, раз)
    type TEXT NOT NULL,                     -- Тип челленджа (steps, water, workout_time, distance, exercises)
    motivation TEXT NOT NULL,               -- Мотивационное сообщение
    created_at TIMESTAMPTZ DEFAULT NOW()   -- Дата создания
);

-- Создаем индексы для быстрого поиска
CREATE INDEX IF NOT EXISTS idx_weekly_challenges_week_start ON weekly_challenges(week_start);
CREATE INDEX IF NOT EXISTS idx_weekly_challenges_type ON weekly_challenges(type);

-- 2. Таблица отслеживания шагов
CREATE TABLE IF NOT EXISTS steps_tracking (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL,                     -- Дата (только дата, без времени)
    steps INTEGER NOT NULL DEFAULT 0,       -- Количество шагов за день
    updated_at TIMESTAMPTZ DEFAULT NOW(),   -- Последнее обновление
    
    -- Уникальность: один пользователь может иметь только одну запись на дату
    UNIQUE(user_id, date)
);

-- Создаем индексы для быстрого поиска
CREATE INDEX IF NOT EXISTS idx_steps_tracking_user_date ON steps_tracking(user_id, date);
CREATE INDEX IF NOT EXISTS idx_steps_tracking_date ON steps_tracking(date);

-- 3. Добавляем поле для уведомлений в таблицу profiles (если еще нет)
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS notifications_enabled BOOLEAN DEFAULT true;

-- Создаем индекс для поиска пользователей с включенными уведомлениями
CREATE INDEX IF NOT EXISTS idx_profiles_notifications ON profiles(notifications_enabled) WHERE notifications_enabled = true;

-- 4. Функция для автоматического обновления updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Создаем триггер для автоматического обновления updated_at в steps_tracking
DROP TRIGGER IF EXISTS update_steps_tracking_updated_at ON steps_tracking;
CREATE TRIGGER update_steps_tracking_updated_at
    BEFORE UPDATE ON steps_tracking
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 5. Включаем Row Level Security (RLS) - упрощенная версия
ALTER TABLE weekly_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE steps_tracking ENABLE ROW LEVEL SECURITY;

-- 6. Простые политики доступа для weekly_challenges
DROP POLICY IF EXISTS "Allow all read access to weekly_challenges" ON weekly_challenges;
CREATE POLICY "Allow all read access to weekly_challenges" ON weekly_challenges
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow service role full access to weekly_challenges" ON weekly_challenges;
CREATE POLICY "Allow service role full access to weekly_challenges" ON weekly_challenges
    FOR ALL USING (auth.role() = 'service_role');

-- 7. Простые политики доступа для steps_tracking
DROP POLICY IF EXISTS "Allow all read access to steps_tracking" ON steps_tracking;
CREATE POLICY "Allow all read access to steps_tracking" ON steps_tracking
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow service role full access to steps_tracking" ON steps_tracking;
CREATE POLICY "Allow service role full access to steps_tracking" ON steps_tracking
    FOR ALL USING (auth.role() = 'service_role');

-- 8. Комментарии к таблицам
COMMENT ON TABLE weekly_challenges IS 'Еженедельные челленджи для пользователей';
COMMENT ON TABLE steps_tracking IS 'Отслеживание шагов пользователей по дням';

COMMENT ON COLUMN weekly_challenges.week_start IS 'Дата начала недели (понедельник) для челленджа';
COMMENT ON COLUMN weekly_challenges.target_value IS 'Целевое значение для выполнения челленджа';
COMMENT ON COLUMN weekly_challenges.type IS 'Тип челленджа: steps, water, workout_time, distance, exercises';

COMMENT ON COLUMN steps_tracking.date IS 'Дата учета шагов (только дата, без времени)';
COMMENT ON COLUMN steps_tracking.steps IS 'Количество шагов за указанную дату';

-- 9. Создаем тестовый челлендж на текущую неделю
INSERT INTO weekly_challenges (week_start, title, description, target_value, unit, type, motivation) 
VALUES 
    (
        date_trunc('week', NOW() AT TIME ZONE 'Europe/Moscow') + INTERVAL '1 day',
        'Пройти 70,000 шагов за неделю!',
        'Активность - основа здоровья! Двигайтесь каждый день и достигните 70,000 шагов за неделю. Это примерно 10,000 шагов в день.',
        70000,
        'шагов',
        'steps',
        'Каждый шаг приближает вас к цели! Вы сможете это сделать! 💪'
    )
ON CONFLICT (week_start) DO NOTHING;

-- Успешное создание всех таблиц
SELECT 'Все таблицы для системы челленджей успешно созданы! 🎉' as result; 

ALTER TABLE weekly_challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE steps_tracking DISABLE ROW LEVEL SECURITY;

-- 📊 АДАПТИРОВАННАЯ SQL СХЕМА ДЛЯ СИСТЕМЫ ЕЖЕНЕДЕЛЬНОЙ АНАЛИТИКИ ВЕСА
-- Совместимо с существующей базой данных

-- Таблица подписок пользователей (адаптировано под существующую схему)
CREATE TABLE IF NOT EXISTS public.user_subscriptions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    plan VARCHAR(20) NOT NULL DEFAULT 'free', -- 'free', 'premium', 'vip'
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE, -- NULL для бесплатной подписки
    payment_id VARCHAR(255), -- ID платежа для отслеживания
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id)
);

-- Таблица ежедневного использования (адаптировано)
CREATE TABLE IF NOT EXISTS public.daily_usage (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    photos_analyzed INTEGER NOT NULL DEFAULT 0,
    ai_questions_asked INTEGER NOT NULL DEFAULT 0,
    workouts_generated INTEGER NOT NULL DEFAULT 0,
    manual_entries INTEGER NOT NULL DEFAULT 0, -- ручной ввод еды
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, date)
);

-- Таблица истории веса (расширение существующих данных)
CREATE TABLE IF NOT EXISTS public.weight_history (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    weight_kg DECIMAL(5,2) NOT NULL, -- Совместимо с profiles.weight_kg
    notes TEXT, -- Дополнительные заметки
    source VARCHAR(20) DEFAULT 'manual', -- 'manual', 'profile_update', 'weekly_check'
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Таблица для напоминаний о весе
CREATE TABLE IF NOT EXISTS public.weight_reminders (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    reminder_date DATE NOT NULL,
    reminder_type VARCHAR(20) DEFAULT 'weekly', -- 'weekly', 'monthly', 'custom'
    is_sent BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, reminder_date)
);

-- Индексы для оптимизации запросов
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_id ON public.user_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_plan ON public.user_subscriptions(plan);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_active ON public.user_subscriptions(is_active);

CREATE INDEX IF NOT EXISTS idx_daily_usage_user_id ON public.daily_usage(user_id);
CREATE INDEX IF NOT EXISTS idx_daily_usage_date ON public.daily_usage(date);
CREATE INDEX IF NOT EXISTS idx_daily_usage_user_date ON public.daily_usage(user_id, date);

CREATE INDEX IF NOT EXISTS idx_weight_history_user_id ON public.weight_history(user_id);
CREATE INDEX IF NOT EXISTS idx_weight_history_recorded_at ON public.weight_history(recorded_at);
CREATE INDEX IF NOT EXISTS idx_weight_history_user_recorded ON public.weight_history(user_id, recorded_at);

CREATE INDEX IF NOT EXISTS idx_weight_reminders_user_id ON public.weight_reminders(user_id);
CREATE INDEX IF NOT EXISTS idx_weight_reminders_date ON public.weight_reminders(reminder_date);

-- Функция для увеличения счетчика использования (адаптированная)
CREATE OR REPLACE FUNCTION increment_usage(
    p_user_id BIGINT,
    p_date DATE,
    p_field VARCHAR(50)
)
RETURNS VOID AS $$
BEGIN
    INSERT INTO public.daily_usage (user_id, date, photos_analyzed, ai_questions_asked, workouts_generated, manual_entries)
    VALUES (p_user_id, p_date, 
            CASE WHEN p_field = 'photos_analyzed' THEN 1 ELSE 0 END,
            CASE WHEN p_field = 'ai_questions_asked' THEN 1 ELSE 0 END,
            CASE WHEN p_field = 'workouts_generated' THEN 1 ELSE 0 END,
            CASE WHEN p_field = 'manual_entries' THEN 1 ELSE 0 END)
    ON CONFLICT (user_id, date) 
    DO UPDATE SET
        photos_analyzed = CASE WHEN p_field = 'photos_analyzed' THEN daily_usage.photos_analyzed + 1 ELSE daily_usage.photos_analyzed END,
        ai_questions_asked = CASE WHEN p_field = 'ai_questions_asked' THEN daily_usage.ai_questions_asked + 1 ELSE daily_usage.ai_questions_asked END,
        workouts_generated = CASE WHEN p_field = 'workouts_generated' THEN daily_usage.workouts_generated + 1 ELSE daily_usage.workouts_generated END,
        manual_entries = CASE WHEN p_field = 'manual_entries' THEN daily_usage.manual_entries + 1 ELSE daily_usage.manual_entries END,
        updated_at = timezone('utc'::text, now());
END;
$$ LANGUAGE plpgsql;

-- Функция для получения профиля пользователя по telegram_id (адаптированная)
CREATE OR REPLACE FUNCTION get_user_profile_by_telegram_id(p_telegram_id BIGINT)
RETURNS TABLE(
    id BIGINT,
    telegram_id BIGINT,
    username TEXT,
    first_name TEXT,
    gender TEXT,
    age INT,
    height_cm INT,
    weight_kg NUMERIC(5,2),
    target_weight_kg NUMERIC,
    goal TEXT,
    timeframe_months INT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id,
        p.telegram_id,
        p.username,
        p.first_name,
        p.gender,
        p.age,
        p.height_cm,
        p.weight_kg,
        p.target_weight_kg,
        p.goal,
        p.timeframe_months
    FROM public.profiles p
    WHERE p.telegram_id = p_telegram_id;
END;
$$ LANGUAGE plpgsql;

-- Функция для получения статистики использования (адаптированная)
CREATE OR REPLACE FUNCTION get_user_usage_stats(p_user_id BIGINT)
RETURNS TABLE(
    today_photos INTEGER,
    today_questions INTEGER,
    today_manual_entries INTEGER,
    month_workouts INTEGER,
    total_weight_records INTEGER,
    last_weight DECIMAL(5,2),
    weight_trend VARCHAR(20),
    current_weight DECIMAL(5,2)
) AS $$
DECLARE
    this_month_start DATE := DATE_TRUNC('month', CURRENT_DATE)::DATE;
    today DATE := CURRENT_DATE;
BEGIN
    RETURN QUERY
    SELECT 
        COALESCE(du.photos_analyzed, 0) as today_photos,
        COALESCE(du.ai_questions_asked, 0) as today_questions,
        COALESCE(du.manual_entries, 0) as today_manual_entries,
        COALESCE(monthly.total_workouts, 0)::INTEGER as month_workouts,
        COALESCE(weight_stats.total_records, 0)::INTEGER as total_weight_records,
        weight_stats.last_weight,
        weight_stats.trend,
        profile_weight.current_weight
    FROM (
        SELECT p_user_id as user_id
    ) u
    LEFT JOIN public.daily_usage du ON du.user_id = u.user_id AND du.date = today
    LEFT JOIN (
        SELECT 
            user_id,
            SUM(workouts_generated) as total_workouts
        FROM public.daily_usage 
        WHERE user_id = p_user_id 
        AND date >= this_month_start
        GROUP BY user_id
    ) monthly ON monthly.user_id = u.user_id
    LEFT JOIN (
        SELECT 
            user_id,
            COUNT(*) as total_records,
            (SELECT weight_kg FROM public.weight_history WHERE user_id = p_user_id ORDER BY recorded_at DESC LIMIT 1) as last_weight,
            CASE 
                WHEN COUNT(*) < 2 THEN 'insufficient_data'
                WHEN (SELECT weight_kg FROM public.weight_history WHERE user_id = p_user_id ORDER BY recorded_at DESC LIMIT 1) > 
                     (SELECT weight_kg FROM public.weight_history WHERE user_id = p_user_id ORDER BY recorded_at DESC LIMIT 1 OFFSET 1) 
                THEN 'increasing'
                WHEN (SELECT weight_kg FROM public.weight_history WHERE user_id = p_user_id ORDER BY recorded_at DESC LIMIT 1) < 
                     (SELECT weight_kg FROM public.weight_history WHERE user_id = p_user_id ORDER BY recorded_at DESC LIMIT 1 OFFSET 1) 
                THEN 'decreasing'
                ELSE 'stable'
            END as trend
        FROM public.weight_history 
        WHERE user_id = p_user_id
        GROUP BY user_id
    ) weight_stats ON weight_stats.user_id = u.user_id
    LEFT JOIN (
        SELECT 
            id as user_id,
            weight_kg as current_weight
        FROM public.profiles
        WHERE id = p_user_id
    ) profile_weight ON profile_weight.user_id = u.user_id;
END;
$$ LANGUAGE plpgsql;

-- Включаем Row Level Security
ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weight_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weight_reminders ENABLE ROW LEVEL SECURITY;

-- Простые политики для полного доступа (совместимо с существующим подходом)
CREATE POLICY "Allow public all operations on user_subscriptions" 
ON public.user_subscriptions FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Allow public all operations on daily_usage" 
ON public.daily_usage FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Allow public all operations on weight_history" 
ON public.weight_history FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Allow public all operations on weight_reminders" 
ON public.weight_reminders FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

-- Комментарии к таблицам
COMMENT ON TABLE public.user_subscriptions IS 'Подписки пользователей (free, premium, vip) - адаптировано под существующую схему';
COMMENT ON TABLE public.daily_usage IS 'Ежедневная статистика использования функций - адаптировано';
COMMENT ON TABLE public.weight_history IS 'История записей веса пользователей - дополняет profiles.weight_kg';
COMMENT ON TABLE public.weight_reminders IS 'Напоминания о записи веса';

COMMENT ON COLUMN public.weight_history.weight_kg IS 'Вес в килограммах (совместимо с profiles.weight_kg)';
COMMENT ON COLUMN public.weight_history.source IS 'Источник записи: manual, profile_update, weekly_check';
COMMENT ON COLUMN public.user_subscriptions.expires_at IS 'Дата истечения подписки (NULL для бесплатной)';

-- Функция для автоматического копирования веса из profiles в weight_history при обновлении
CREATE OR REPLACE FUNCTION sync_weight_to_history()
RETURNS TRIGGER AS $$
BEGIN
    -- Если вес изменился, добавляем запись в историю
    IF OLD.weight_kg IS DISTINCT FROM NEW.weight_kg AND NEW.weight_kg IS NOT NULL THEN
        INSERT INTO public.weight_history (user_id, weight_kg, source, recorded_at)
        VALUES (NEW.id, NEW.weight_kg, 'profile_update', timezone('utc'::text, now()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Создаем триггер для автоматической синхронизации
DROP TRIGGER IF EXISTS trigger_sync_weight_to_history ON public.profiles;
CREATE TRIGGER trigger_sync_weight_to_history
    AFTER UPDATE OF weight_kg ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION sync_weight_to_history();

-- Добавляем колонку для уведомлений, если ее еще нет
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS notifications_enabled BOOLEAN DEFAULT true;

-- Создаем тестовые подписки для разработки (закомментировано для безопасности)
/*
INSERT INTO public.user_subscriptions (user_id, plan, is_active) 
SELECT id, 'vip', true FROM public.profiles WHERE telegram_id = YOUR_TELEGRAM_ID
ON CONFLICT (user_id) DO NOTHING;
*/

-- Сообщение об успешном создании
SELECT 'Система еженедельной аналитики веса успешно адаптирована под существующую схему БД! 🎉' as result; 

ALTER TABLE public.user_subscriptions
ADD COLUMN IF NOT EXISTS promo_activated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS promo_expires_at TIMESTAMPTZ;

COMMENT ON COLUMN public.user_subscriptions.promo_activated_at IS 'Время, когда пользователь активировал промо-период';
COMMENT ON COLUMN public.user_subscriptions.promo_expires_at IS 'Время, когда промо-период истекает';


ALTER TABLE public.user_subscriptions
ADD COLUMN IF NOT EXISTS promo_activated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS promo_expires_at TIMESTAMPTZ;

COMMENT ON COLUMN public.user_subscriptions.promo_activated_at IS 'Время, когда пользователь активировал промо-период';
COMMENT ON COLUMN public.user_subscriptions.promo_expires_at IS 'Время, когда промо-период истекает';


-- Создание таблицы для отслеживания ежедневного использования
CREATE TABLE IF NOT EXISTS public.daily_usage (
    id SERIAL PRIMARY KEY,
    telegram_id BIGINT NOT NULL,
    date DATE NOT NULL,
    photos_processed INTEGER DEFAULT 0,
    ai_questions INTEGER DEFAULT 0,
    meal_logs INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(telegram_id, date)
);

-- Создание таблицы для отслеживания действий пользователей
CREATE TABLE IF NOT EXISTS public.user_actions (
    id SERIAL PRIMARY KEY,
    telegram_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    data JSONB
);

-- Индексы для производительности
CREATE INDEX IF NOT EXISTS idx_daily_usage_telegram_id ON public.daily_usage(telegram_id);
CREATE INDEX IF NOT EXISTS idx_daily_usage_date ON public.daily_usage(date);
CREATE INDEX IF NOT EXISTS idx_user_actions_telegram_id ON public.user_actions(telegram_id);
CREATE INDEX IF NOT EXISTS idx_user_actions_type ON public.user_actions(action_type);
CREATE INDEX IF NOT EXISTS idx_user_actions_created_at ON public.user_actions(created_at);

-- Включение RLS
ALTER TABLE public.daily_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_actions ENABLE ROW LEVEL SECURITY;

-- Политики безопасности
CREATE POLICY "Allow public all operations on daily_usage"
ON public.daily_usage FOR ALL
TO public
USING (true);

CREATE POLICY "Allow public all operations on user_actions"
ON public.user_actions FOR ALL
TO public
USING (true);

-- Комментарии к таблицам
COMMENT ON TABLE public.daily_usage IS 'Ежедневное использование функций пользователями';
COMMENT ON COLUMN public.daily_usage.telegram_id IS 'ID пользователя в Telegram';
COMMENT ON COLUMN public.daily_usage.date IS 'Дата использования';
COMMENT ON COLUMN public.daily_usage.photos_processed IS 'Количество обработанных фото за день';
COMMENT ON COLUMN public.daily_usage.ai_questions IS 'Количество вопросов к ИИ за день';
COMMENT ON COLUMN public.daily_usage.meal_logs IS 'Количество записей о еде за день';

COMMENT ON TABLE public.user_actions IS 'Лог действий пользователей';
COMMENT ON COLUMN public.user_actions.telegram_id IS 'ID пользователя в Telegram';
COMMENT ON COLUMN public.user_actions.action_type IS 'Тип действия';
COMMENT ON COLUMN public.user_actions.data IS 'Дополнительные данные о действии';

-- 📊 ОБНОВЛЕНИЕ ТАБЛИЦЫ ПОДПИСОК ДЛЯ СИСТЕМЫ ПРОМО

-- Добавляем колонки для промо-системы если их нет
ALTER TABLE public.user_subscriptions 
ADD COLUMN IF NOT EXISTS promo_activated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS promo_expires_at TIMESTAMP WITH TIME ZONE;

-- Обновим существующие записи для бесплатных пользователей
UPDATE public.user_subscriptions 
SET plan = 'free' 
WHERE plan IS NULL;

-- Создаем индексы для оптимизации
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_promo_expires 
ON public.user_subscriptions(promo_expires_at) 
WHERE promo_expires_at IS NOT NULL;

-- Функция для получения подписки пользователя
CREATE OR REPLACE FUNCTION get_user_subscription_by_telegram_id(p_telegram_id BIGINT)
RETURNS TABLE(
    tier TEXT,
    expires_at TIMESTAMP WITH TIME ZONE,
    promo_activated_at TIMESTAMP WITH TIME ZONE,
    promo_expires_at TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        us.plan as tier,
        us.expires_at,
        us.promo_activated_at,
        us.promo_expires_at
    FROM public.user_subscriptions us
    JOIN public.profiles p ON p.id = us.user_id
    WHERE p.telegram_id = p_telegram_id;
END;
$$ LANGUAGE plpgsql;

-- === ИНТЕГРАЦИЯ С ЮKASSA ===

-- Таблица для отслеживания платежей через ЮKassa
CREATE TABLE IF NOT EXISTS public.yukassa_payments (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    telegram_id BIGINT NOT NULL,
    payment_id UUID NOT NULL UNIQUE, -- ID платежа из ЮKassa
    amount DECIMAL(10,2) NOT NULL, -- Сумма платежа
    currency VARCHAR(3) NOT NULL DEFAULT 'RUB',
    subscription_tier VARCHAR(20) NOT NULL, -- 'progress' или 'maximum'
    status VARCHAR(20) NOT NULL DEFAULT 'pending', -- pending, succeeded, failed, canceled
    payment_url TEXT, -- Ссылка для оплаты
    confirmation_token TEXT, -- Токен подтверждения от ЮKassa
    paid_at TIMESTAMP WITH TIME ZONE, -- Время успешной оплаты
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL, -- Время истечения ссылки
    metadata JSONB, -- Дополнительные данные от ЮKassa
    webhook_received_at TIMESTAMP WITH TIME ZONE, -- Время получения webhook
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Индексы для быстрого поиска платежей
CREATE INDEX IF NOT EXISTS idx_yukassa_payments_user_id ON public.yukassa_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_yukassa_payments_telegram_id ON public.yukassa_payments(telegram_id);
CREATE INDEX IF NOT EXISTS idx_yukassa_payments_payment_id ON public.yukassa_payments(payment_id);
CREATE INDEX IF NOT EXISTS idx_yukassa_payments_status ON public.yukassa_payments(status);
CREATE INDEX IF NOT EXISTS idx_yukassa_payments_created_at ON public.yukassa_payments(created_at);

-- Включаем Row Level Security
ALTER TABLE public.yukassa_payments ENABLE ROW LEVEL SECURITY;

-- Политики для полного доступа
CREATE POLICY "Allow public all operations on yukassa_payments" 
ON public.yukassa_payments FOR ALL 
TO public 
USING (true) 
WITH CHECK (true);

-- Функция для активации подписки после успешной оплаты
CREATE OR REPLACE FUNCTION activate_subscription_after_payment(
    p_telegram_id BIGINT,
    p_subscription_tier VARCHAR(20),
    p_payment_id UUID
)
RETURNS BOOLEAN AS $$
DECLARE
    v_user_id BIGINT;
    v_expires_at TIMESTAMP WITH TIME ZONE;
BEGIN
    -- Получаем user_id по telegram_id
    SELECT id INTO v_user_id 
    FROM public.profiles 
    WHERE telegram_id = p_telegram_id;
    
    IF v_user_id IS NULL THEN
        RETURN FALSE;
    END IF;
    
    -- Вычисляем дату истечения подписки (30 дней)
    v_expires_at := timezone('utc'::text, now()) + INTERVAL '30 days';
    
    -- Обновляем или создаем запись подписки
    INSERT INTO public.user_subscriptions (user_id, plan, tier, is_active, expires_at, payment_id, updated_at)
    VALUES (v_user_id, p_subscription_tier, p_subscription_tier, TRUE, v_expires_at, p_payment_id::TEXT, timezone('utc'::text, now()))
    ON CONFLICT (user_id) 
    DO UPDATE SET
        plan = p_subscription_tier,
        tier = p_subscription_tier,
        is_active = TRUE,
        expires_at = v_expires_at,
        payment_id = p_payment_id::TEXT,
        updated_at = timezone('utc'::text, now());
    
    -- Отмечаем платеж как успешный
    UPDATE public.yukassa_payments
    SET 
        status = 'succeeded',
        paid_at = timezone('utc'::text, now()),
        webhook_received_at = timezone('utc'::text, now()),
        updated_at = timezone('utc'::text, now())
    WHERE payment_id = p_payment_id;
    
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

-- Комментарии к таблице
COMMENT ON TABLE public.yukassa_payments IS 'Отслеживание платежей через ЮKassa API';
COMMENT ON COLUMN public.yukassa_payments.payment_id IS 'Уникальный ID платежа от ЮKassa';
COMMENT ON COLUMN public.yukassa_payments.amount IS 'Сумма платежа в рублях';
COMMENT ON COLUMN public.yukassa_payments.subscription_tier IS 'Тип подписки: progress (199₽) или maximum (349₽)';
COMMENT ON COLUMN public.yukassa_payments.status IS 'Статус платежа: pending, succeeded, failed, canceled';
COMMENT ON COLUMN public.yukassa_payments.confirmation_token IS 'Токен для подтверждения платежа';
COMMENT ON COLUMN public.yukassa_payments.metadata IS 'Дополнительные данные от ЮKassa в формате JSON';
